#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun 12 08:31:20 2018

@author: f095
"""

import numpy as np

Array1 = np.array([(1,'A'),(5,'B'),(10,'C')],dtype = [('Spalte1',np.int),('Spalte2','S10')])
Array1.dtype
Array1['Spalte2']